"""Data models for the response agent."""

from dataclasses import dataclass


@dataclass(frozen=True)
class GeneratedResponse:
    """The final response generated by the Response Agent. """
    
    content: str


@dataclass(frozen=True)
class FormattedContext:
    """A deterministic formatted context representation."""
    
    text: str


@dataclass(frozen=True)
class Prompt:
    system_prompt: str
    user_prompt: str
